### PR TITLE
Create 3-1.md

### PR DESCRIPTION
**Pull request by LaconicTranslator**
Starting with chapter 3 just in case chapter 2 is already taken by someone.

### CODE REVIEW

**Comment by cipi1965** [comment]
Is it ready to merge?

**Comment by LaconicTranslator** [comment]
Yes. Ready to merge. Is it OK if I go file by file? Or is it better to make less frequent requests?

**Comment by cipi1965** [comment]
It’s perfect if you go file by file as other translators can do others

**Comment by LaconicTranslator** [comment]
Got it.

**Pull request merged**
