### PR TITLE
Added hu directory, partial translation of 0-0

### PR DESCRIPTION
**Pull request by kicsipixel**

### CODE REVIEW

**Comment by twostraws** [comment]
@chosa91: Do you want to try adding those changes as new PRs?

**Comment by chosa91** [comment]
@twostraws I'm already contacted w/ @kicsipixel and I'll start from the end and after polish the parts

**Comment by twostraws** [comment]
Awesome!

**Comment by kicsipixel** [comment]
@twostraws, we are counting on you in the Hungarian translation too.

**Pull request merged**
