### PR TITLE
Adding contributor: data and png.

### PR DESCRIPTION
**Pull request by mleFR95deviOS**
Just adding some data about me and png

### CODE REVIEW

**Comment by twostraws** [comment]
This does need to be accompanied by some actual translation too :)

**Comment by twostraws** [comment]
This is becoming a really big PR, which I’m sure wasn’t your intention. You might want to consider closing this, pulling a clean copy of the repository, and add your changes.

**Comment by mleFR95deviOS** [comment]
hi Paul, 
sorry, but i don't understand your message, i am translating my first file, but I didn’t send a PR  !
 I made a big mistake ?

Michel

**Comment by Rubenfer** [comment]
Hi Michel,

You created a PR (we closed it due to a issue). If you’re working on a file translation, please, open a issue with this name: “Taken: language_code/file_number.md” to avoid other do your same         
Then, when you will finished the translation, you need to pull this repo, commit your changes, and finally open a PR.

Thanks!

**Pull request closed without merging**
