### PR TITLE
Start ar/0-1.md translation WIP

### PR DESCRIPTION
**Pull request by almaleh**
This translation is in progress

### CODE REVIEW

**Comment by Rubenfer** [comment]
Hi @almaleh,
please, if you're working on a translation, the correct way to do it is the following:

1. You choose a tutorial to translate
2. You open a Issue with format: "Taken: ar/0-1.md"
3. You translate the tutorial
4. **When you finished the translation, you open the Pull Request.**

Read README file to more info.

**Comment by twostraws** [comment]
This has been open for almost two weeks now. Is everything OK?

**Comment by almaleh** [comment]
> This has been open for almost two weeks now. Is everything OK?

Sorry about that! I shouldn’t have opened this early. I’ll commit this section by the end of this week

**Comment by twostraws** [comment]
It’s OK! I’ll close this, and you can reopen when you’re ready 👍

**Pull request closed without merging**
