### PR TITLE
Added Kurdish lang file

### PR DESCRIPTION
**Pull request by rawandsaeed**

### CODE REVIEW

**Comment by rawandsaeed** [comment]
Added Kurdish Translation

**Comment by rawandsaeed** [comment]
Thanks Paul, 

I submitted the code according to 
ISO 639-2 Code. 

However, according to  ISO 639-1 Code it is “ku”. 

Sorry for the inconvenience I can push again as “ku”. 

Let me know if I new to push again?

**Comment by twostraws** [comment]
Please stick with “ku” for now – thank you!

**Comment by rawandsaeed** [comment]
Will do. Thanks

**Comment by rawandsaeed** [comment]
Yes I will do that.

**Pull request merged**
