### PR TITLE
WIP: (es) Spanish Translation for 0-6.md

### PR DESCRIPTION
**Pull request by nhiddink**
Work in progress PR to show others that I'm working on this section.

### CODE REVIEW

**Comment by nhiddink** [comment]
@frivas I can't seem to edit/close the open issue on this one. Also, how did I do on the translation? 😬

**Comment by frivas** [comment]
Hello @nhiddink as we talked over Slack. There are a few things I would suggest changing:

- Line 17: "that will print"... can be translated as "esto mostrará" that means "this will show", because in Spanish it is similar or at least understandable. "Imprimiere" is a different tense or conjunction of the verb. In this particular case it can be substituted by a similar expression that indicates showing an output. "and" has to be translated "y". I am translating "results pane" as "panel de resultados". 

- Line 19: The first sentence needs some polishing like: "La posición de un elemento del arreglo se llama índice, por lo que puedes leer cualquier elemento del arreglo utilizando su índice". When it comes to arrays, "items" are translated to "elementos" (or elemento for singular). For example the sentence "nuestro arreglo contiene tres datos" we could say "contiene tres elementos" it is more accurate. "aplicación" is a female word so it would be "una aplicación". "crash" is better translated to "fallar", at least in this context.

- Line 21: The first sentence as written is complicated to understand, so I would suggest something like "Ya que has creado el arreglo utilizando 3 cadenas de caracteres _(Strings)_". "caracteres" without the acento on the second "a" refers to a character whereas with acento refers to a characteristic of a person like behaviour-wise. I would recommend to change "imprimiere"  for "mostrará" (will show). This second sentence, I would suggest something like "Puede confirmar esto utilizando el comando que, en el _playground_, muestra el tipo de datos de una variable, de esta forma:"

I would suggest to change "panel gráfico" by "panel de resultados"

Line 26: "diciendo que Swift considera que `songs` es un arreglo de cadena de caracteres"

The translation for this sentence is missing:
Let's say you made a mistake, and accidentally put a number on the end of the array. Try this now and see what the results pane prints:

It would be something like:
"Digamos que cometes un error y, de forma accidental, insertas un número al final del arreglo. Escribe lo siguiente y observa lo que muestra el panel de resultados".

Line 31: I think Paul uses the second person of "you" which translates to "tu", it sounds more friendly, so in this case it can be translated like "te voy a mostrar...". I have to say this is a complicated sentence to translate, I would suggest something like this:
"En este momento, verás un error. Este error no es causado porque Swift no puede manejar arreglos mezclados como este -¡Te voy a enseñar esto en un momento! - más bien es porque Swift está ayudándonos.". Then. "mejor dicho" refers to correcting something, in this context what Pual is trying to say is "Lo que quieres decir" which means "which means..." or you can use something like "En perfecto Español...". Then I would change a few words in the next sentence like "it looks like" is better translated to "parece que". The way to translate "designed" is "diseñado". "for" is better translated to "para" and "contain" is better translated to "almacenar", "contener" is the correct translation however in this context it is not used. The whole sentence would be something like "Parece que este arreglo esta diseñado para almacenar muchos tipos de datos - si realmente significa eso, por favor déjalo explícito". 

Line 33: I am not translating "type safety" because I am not aware of a correct/right/known/accepted translation so I just leave it as is. Then, "este caso en particular fuera un accidente" it would be better translated to "este caso en particular fue un accidente". "anotaciónes de tipo", first "anotaciones" does not have an acento in that letter and also the right translation for that would be "especificación de tipo" because it refers to the fact that you are explicitly telling Swift the data type of a variable or constant. The last sentence is better translated like "Esto solo se refiere a que en algún momento habrá un arreglo y este almacenará cadenas de caracteres".

Like 37: "cadena" is a female word so the articles are "la cadena", "una cadena", "las cadenas", "unas cadenas" and so on.

Line 39: "Si realmente quieres que el arreglo pueda almacenar cualquier tipo de dato, utiliza el tipo de dato especial `Any` así:" 

Line 43: you do not need to use "los", it is like using "the" when it is not necessary. I am really sorry I do not know how to explain this in a better way hahaha!

Line 45: "Si (creas or declaras) un arreglo de la forma mostrada arriba, Swift creará el arreglo y almacenará los valores que hemos especificado. Las cosas no son tan simples si queremos crear un arreglo para llenarlo luego - esta sintaxis no va funciona" (doesn't work is translated to present tense in Spanish - no funciona)

Line 50: "razón" is a female word so everything related to it should be in its female form like "quisquillosa" because it refers to "la razón", also you can use the word "pedante" which is a direct translation of "pedantic" however quisquilloso/a sounds better. "at first" in this context is better translated to "a primera vista" or "en principio". "implicaciones" is a female word and also is in its plural form so it would be like "profundas implicaciones" however "profundas" sounds weird in this context so it would be better to use "importantes" (important, critical or something like that). you can safely remove "subyacente". I know this expression is difficult to translate because in Spanish we use a different expression : "I am afraid you're stuck with it", it can be translated to something like "Lo siento pero tienes que vivir con ello" it is like "I am sorry but you have to live with it". "pero esto no inicia el arreglo" is better like "esto no crea el arreglo". 

Line 52: "maneras para.." is better like "maneras de" (in this context). You can remove "unas" too. "y la una que" you can remove "una". "desde" is better like "por". "esto" better like "esta" because it refers to "manera" which is a female word so "la manera", "las maneras", etc.

Line 58: This would be better like "También verás frecuentemente este constructor".

Line 66: This would be better like "Puedes utilizar un conjunto limitado de operadores sobre los arreglos". "Puedes combinar dos arreglos utilizando el operador `+`, así:"

Sorry if this has been too long or complicated to understand. I have no experience explaining Spanish in English and moreover my English needs a lot of polishing and corrections. I hope this help you to learn more. 😄 

Have a great one!

**Comment by nhiddink** [comment]
Wow! Thanks for the feedback @frivas! I'm going to take a look at these one by one and add them as I go along. So far everything makes sense, I'm realizing just how important context is to the overall meaning of everything... 🤓

**Comment by frivas** [comment]
@nhiddink no worries :D That is exactly what happens to me when speaking in English, it is hard sometimes how a native would phrase something, which words are correct and so on. haha! 😄 I have to say I admire that you do this it is very cool. Please keep up.

**Comment by nhiddink** [comment]
☑️ **This makes sense, I also changed imprimiere to eso mostrará on line 26.** 
Line 17: "that will print"... can be translated as "esto mostrará" that means "this will show", because in Spanish it is similar or at least understandable. "Imprimiere" is a different tense or conjunction of the verb. In this particular case it can be substituted by a similar expression that indicates showing an output. "and" has to be translated "y". I am translating "results pane" as "panel de resultados". 

☑️ **I wondered what order was best when I wrote the first sentence, I think it's much better now! I've also gone through and changed dato to elemento when talking about arrays. I'll try to use the terms from the book you posted on the wiki when I don't know.**
Line 19: The first sentence needs some polishing like: "La posición de un elemento del arreglo se llama índice, por lo que puedes leer cualquier elemento del arreglo utilizando su índice". When it comes to arrays, "items" are translated to "elementos" (or elemento for singular). For example the sentence "nuestro arreglo contiene tres datos" we could say "contiene tres elementos" it is more accurate. "aplicación" is a female word so it would be "una aplicación". "crash" is better translated to "fallar", at least in this context.

☑️ **I had no idea about caracteres vs carácteres, good to know! 🧐 I fixed this and added the other changes.**
Line 21: The first sentence as written is complicated to understand, so I would suggest something like "Ya que has creado el arreglo utilizando 3 cadenas de caracteres (Strings)". "caracteres" without the acento on the second "a" refers to a character whereas with acento refers to a characteristic of a person like behaviour-wise. I would recommend to change "imprimiere" for "mostrará" (will show). This second sentence, I would suggest something like "Puede confirmar esto utilizando el comando que, en el playground, muestra el tipo de datos de una variable, de esta forma:"

I would suggest to change "panel gráfico" by "panel de resultados"

☑️ **Oops, good catch. 👍**
Line 26: "diciendo que Swift considera que songs es un arreglo de cadena de caracteres"
The translation for this sentence is missing:
Let's say you made a mistake, and accidentally put a number on the end of the array. Try this now and see what the results pane prints:

It would be something like:
"Digamos que cometes un error y, de forma accidental, insertas un número al final del arreglo. Escribe lo siguiente y observa lo que muestra el panel de resultados".

☑️ **❗️This is a good point, and we should add this to the wiki so everyone knows to use the informal conjugations. I'm going to go through and change this throughout and use it going forward. I like your suggestion for "lo que quieres decir" and "parece que". Added those in along with translating designed correctly! Also, almacenar (to store) is a great verb, I bet it came from combining the words alma + cenar, almost like "feed the soul".**
Line 31: I think Paul uses the second person of "you" which translates to "tu", it sounds more friendly, so in this case it can be translated like "te voy a mostrar...". I have to say this is a complicated sentence to translate, I would suggest something like this:
"En este momento, verás un error. Este error no es causado porque Swift no puede manejar arreglos mezclados como este -¡Te voy a enseñar esto en un momento! - más bien es porque Swift está ayudándonos.". Then. "mejor dicho" refers to correcting something, in this context what Pual is trying to say is "Lo que quieres decir" which means "which means..." or you can use something like "En perfecto Español...". Then I would change a few words in the next sentence like "it looks like" is better translated to "parece que". The way to translate "designed" is "diseñado". "for" is better translated to "para" and "contain" is better translated to "almacenar", "contener" is the correct translation however in this context it is not used. The whole sentence would be something like "Parece que este arreglo esta diseñado para almacenar muchos tipos de datos - si realmente significa eso, por favor déjalo explícito".

☑️ **Sounds good to me, I put "type safety" in bold so everyone knows it's intentional. Also I took a stab at the last sentence, let me know if it makes sense.**
Line 33: I am not translating "type safety" because I am not aware of a correct/right/known/accepted translation so I just leave it as is. Then, "este caso en particular fuera un accidente" it would be better translated to "este caso en particular fue un accidente". "anotaciónes de tipo", first "anotaciones" does not have an acento in that letter and also the right translation for that would be "especificación de tipo" because it refers to the fact that you are explicitly telling Swift the data type of a variable or constant. The last sentence is better translated like "Esto solo se refiere a que en algún momento habrá un arreglo y este almacenará cadenas de caracteres".

☑️ **Got it, I must have missed that one! 😅**
Line 37: "cadena" is a female word so the articles are "la cadena", "una cadena", "las cadenas", "unas cadenas" and so on.

☑️ **Should quieres que be "querías que" here? I thought the pattern was conditional verb first, then subjunctive verb second, in a sentence like this.**
Line 39: "Si realmente quieres que el arreglo pueda almacenar cualquier tipo de dato, utiliza el tipo de dato especial Any así:"

☑️ **No, that makes perfect sense! Thanks.**
Line 43: you do not need to use "los", it is like using "the" when it is not necessary. I am really sorry I do not know how to explain this in a better way hahaha!

☑️ **Good idea, making these changes.**
Line 45: "Si (creas or declaras) un arreglo de la forma mostrada arriba, Swift creará el arreglo y almacenará los valores que hemos especificado. Las cosas no son tan simples si queremos crear un arreglo para llenarlo luego - esta sintaxis no va funciona" (doesn't work is translated to present tense in Spanish - no funciona)

☑️ **I was excited I got to use a fancy word like quisquilloso/a!! 😜 Also "lo sent pero tienes que vivir con ello" makes perfect sense, I read that suggestion and said "Oh of course!" in my head. 😄**
Line 50: "razón" is a female word so everything related to it should be in its female form like "quisquillosa" because it refers to "la razón", also you can use the word "pedante" which is a direct translation of "pedantic" however quisquilloso/a sounds better. "at first" in this context is better translated to "a primera vista" or "en principio". "implicaciones" is a female word and also is in its plural form so it would be like "profundas implicaciones" however "profundas" sounds weird in this context so it would be better to use "importantes" (important, critical or something like that). you can safely remove "subyacente". I know this expression is difficult to translate because in Spanish we use a different expression : "I am afraid you're stuck with it", it can be translated to something like "Lo siento pero tienes que vivir con ello" it is like "I am sorry but you have to live with it". "pero esto no inicia el arreglo" is better like "esto no crea el arreglo".

☑️ **I think at this point I started 😴.**
Line 52: "maneras para.." is better like "maneras de" (in this context). You can remove "unas" too. "y la una que" you can remove "una". "desde" is better like "por". "esto" better like "esta" because it refers to "manera" which is a female word so "la manera", "las maneras", etc.

☑️ **Much better.**
Line 58: This would be better like "También verás frecuentemente este constructor".

☑️ **I like it.**
Line 66: This would be better like "Puedes utilizar un conjunto limitado de operadores sobre los arreglos". "Puedes combinar dos arreglos utilizando el operador +, así:"

**Comment by Rubenfer** [comment]
Hi!

I saw this small typos:

- line 8: "fín" -> fin
- line 10: "un excepción" -> "una excepción"
- line 10: "en su playground" -> "en tu playground"
- line 19: "¡y si tratas eso en una aplicación real va a fallarlo!" -> "¡y si haces eso en una aplicación real va a fallar"

**Comment by Rubenfer** [comment]
@frivas A question about this PR. The line which says: "It doesn't allocate any RAM", in Spanish could be better "Esto no lo asigna a ninguna dirección de memoria", couldn't?

**Comment by Rubenfer** [comment]
Line 64 correction: "[...] y asignarlo a `songs` gracias a la inferencia de tipo. ¡[...] así que no es una sorpresa que lo prefieran muchos programadores!"

**Comment by Rubenfer** [comment]
Line 74: "[...] puedes usar [...]"
Line 33: "[...] El mensaje de error que verás es: [...]

**Comment by nhiddink** [comment]
Thanks @Rubenfer I knew I would miss at least one "tu" form! 😄Also, do you say "lo prefieran" because we don't actually know how many programmers are involved?

**Comment by Rubenfer** [comment]
I say "lo prefieran" because we don't know it for sure. Some devs could use it, but not all.  

(Yes, I know that Spanish verbs are the most difficult thing, even for us)

**Comment by nhiddink** [comment]
Awesome, well @frivas @Rubenfer if you guys are okay with how everything looks, I think we're ready to merge this PR. @twostraws

**Comment by Rubenfer** [comment]
For me it looks good. Let's wait to @frivas review and if he says that's ok we can merge it into master.

Thanks Neil!

**Comment by Rubenfer** [comment]
Please, resubmit it after pull it. Thanks!

**Comment by frivas** [comment]
> @frivas A question about this PR. The line which says: "It doesn't allocate any RAM", in Spanish could be better "Esto no lo asigna a ninguna dirección de memoria", couldn't?

Sorry for the delay I did not see the messages! I will fix that to get notifications. 

I think a good translation would be something "Esto no reserva RAM", when it comes to "allocate" refer to "reserva". However your suggestion sounds good too. You choose. Both are correct.. 

The rest I think is very good. Awesome @nhiddink  and @Rubenfer 😄

**Pull request closed without merging**
