### PR TITLE
ES | 0-19 translation

### PR DESCRIPTION
**Pull request by Rubenfer**
Spanish 0-19 translation, plus 0-18 improvements

### CODE REVIEW

**Comment by frivas** [comment]
Hello @Rubenfer, I have been checking the translation and I have doubts regarding translating, 'properties' to 'atributos'. I think it would be better to stay with 'propiedades'. I have been doing some research on a couple of books about swift and they all mention properties. I remember there was a difference between both terms. In fact attributes refers to something else in Swift. At the Apple's Swift book in page 566, explains what attributes are. What do you think?. If someone else can shine a light here, it would be good. Thank you very much.

**Comment by Rubenfer** [comment]
Yes, you could be right. In my first translation of 0-18 I used "propiedades", but now I've change it to "atributos". Anyway, I don't really know what's the best term.

If you thinks that is better "propiedades" instead of "atributos", I can change it.

**Comment by Rubenfer** [comment]
I'm looking more information about this and I found on "Aprendiendo Swift 3" book:

"Cuando un atributo puede conocerse fuera del contexto del objeto se le denomina propiedad"

I think that both words are correct. In Object Oriented Programming I don't found big differences between "atributo" and "propiedad".

**Comment by twostraws** [comment]
The most important thing you can do is following whatever conventions exist elsewhere. That might be in coding textbooks or blogs, or even just Wikipedia – for now it's safe just to go with whatever people are used to.

**Comment by frivas** [comment]
Ok, awesome!. 😄

**Pull request merged**
