### PR TITLE
[WIP] Small changes and trying a WIP pull request

### PR DESCRIPTION
**Pull request by frivas**
- [x] Draft of first paragraph.
- [x] Reviewing first paragraph for better translations for some expressions, more adequate meaning and grammar.

### CODE REVIEW

**Comment by twostraws** [comment]
I wonder whether adding ES and a filename might work.

**Comment by frivas** [comment]
Do you mean to the comment and/or the title?. 

Seems a very good idea adding it to the comment and the title so it is faster when checking which files are being edit with the PR.

**Comment by twostraws** [comment]
Title. Also, @pdiazmon has suggested opening issues when starting work on a file, which might be even easier?

**Comment by frivas** [comment]
- [x]  Draft of first paragraph.
- [X]  Reviewing first paragraph for better translations for some expressions, more adequate meaning and grammar.
- [X] Added new square image
- [X] Reviewed version of 0-0

**Comment by frivas** [comment]
Yes. I am wondering what would be a good way to let you know when a PR WIP is Done. Also I was thinking about using labels to indicate the name of the file, for example, I would add 2 labels to this PR that are 0-0 and partial while WIP and then 0-0 and done. That way you can filter. 

Thank you very much

**Comment by twostraws** [comment]
Or we could use issues to track WIP and PRs for merging? In these first few weeks I think it's pretty much the wild west 😅

**Comment by frivas** [comment]
That also sounds good. I will give it a try for my next file and see how it goes. This might be crazy until we find a reasonable way to handle all this 😄

**Pull request merged**
