### PR TITLE
Adding Turkish translations.

### PR DESCRIPTION
**Pull request by tanyildiz**

### CODE REVIEW

**Comment by tanyildiz** [comment]
Turkish translations for 0-2.md

**Comment by twostraws** [comment]
Did you modify the English version again?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tanyildiz** [comment]
yes. i don't know other way.
could you help me please how i copy a file and after translation to add
into correct folder?

i've started to translate a new file.
before it finished, i want to do the right way.

sorry..

Niyazi Tanyıldız
0532 263 36 64

**Comment by twostraws** [comment]
When you reply by email it looks like you’re appending your phone number, and that gets posted onto GitHub – you might want to delete that comment and write it again. 

On your computer, where you have all the files from this project, you should start by copying an English file from “en” into “tr”.  Once it’s in there you modify the “tr” copy as much as you want, and the English version won’t change. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tanyildiz** [comment]
thank you both warning and teaching :-)

**Pull request closed without merging**
