### PR TITLE
Urdu Language Translation

### PR DESCRIPTION
**Pull request by Xcode09**

### CODE REVIEW

**Comment by twostraws** [comment]
Can you make sure the JSON and PNG have exactly the same name?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Xcode09** [comment]
> Can you make sure the JSON and PNG have exactly the same name?
> 
> Sent with [GitHawk](http://githawk.com)

Oky

**Comment by Xcode09** [comment]
I change the Name .

**Comment by Xcode09** [comment]
I changed the Name of json file.

**Comment by Xcode09** [comment]
Thanks

**Pull request merged**
